[package]
name = "android"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
note = { path = "../note" }
runtime = { path = "../runtime" }

bincode = "1.3.3"
log = "0.4.16"

jni = { version = "0.19.0", default-features = false }

[lib]
name = "reax"
crate-type = ["cdylib"]
