[workspace]
members = [
    "android",
    "ios",
    "auth",
    "base",
    "note",
    "runtime",
    "util",
    "wasm",
]

[package]
name = "reax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[profile.dev]
debug = false

[profile.release]
opt-level = "z"
lto = true
