[package]
name = "note"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../base" }
runtime = { path = "../runtime" }

aes-gcm-siv = "0.11.1"
base64ct = { version = "1.5.2", features = ["alloc"]}

log = "0.4.16"
once_cell = "1.11.0"
serde_json = "1.0.79"

reqwest = { version = "0.11.10", features = ["rustls-tls", "json"], default-features = false }
serde = { version = "1.0.136", features = ["derive"] }
sqlx = { version = "0.6.1", features = ["runtime-tokio-rustls", "sqlite", "json"], optional = true }
tokio = { version = "1.18.2", features = ["sync"], default-features = false }

[features]
storage = ["dep:sqlx", "base/sqlx"]
