[package]
name = "mavinote-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../base" }
note = { path = "../note" }
runtime = { path = "../runtime" }

wasm-bindgen = "0.2.80"
wasm-bindgen-futures = "0.4.30"
console_error_panic_hook = "0.1.7"

serde_json = "1.0.79"

reqwest = { version = "0.11.10", features = ["rustls-tls"], default-features = false }
